name: wearevolunteenz
description: App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  url_launcher: ^6.0.12
  file_picker: ^5.3.2
  mailer: ^5.0.1
  google_sign_in: ^5.0.3
  http: ^1.1.0
  mime: ^1.0.4
  path_provider: ^2.1.1
  intl: ^0.17.0
  device_info_plus: ^9.1.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets: 
  - assets/logo.png
  - assets/google_signin_buttons/ios/3x/btn_google_light_normal_ios@3x.png
  plugin:
        platforms:
          ios:
            pluginClass: AppDelegate


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

